name: hackathon_chatgpt
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  http: ^0.13.5
  get: 4.6.5
  flutter: 
    sdk: flutter
  loading_animation_widget: ^1.2.0+4
  google_fonts: ^4.0.3
  animated_text_kit: ^4.2.2
  simple_chips_input: ^1.0.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

